# Day02_03_pandas
<font size=5><b>Pandas 활용한 전처리<b></font>
<div align='right'>류 회 성(Hoe Sung Ryu)</div>

 
 
   

    
    
![](https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99298F365B1A19AF0A)

    
    
---

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#이번시간-배울-내용" data-toc-modified-id="이번시간-배울-내용-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>이번시간 배울 내용</a></span></li><li><span><a href="#Pandas-자료구조" data-toc-modified-id="Pandas-자료구조-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Pandas 자료구조</a></span><ul class="toc-item"><li><span><a href="#Pandas-Series-시작하기" data-toc-modified-id="Pandas-Series-시작하기-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Pandas Series 시작하기</a></span></li><li><span><a href="#Pandas-Series-색인" data-toc-modified-id="Pandas-Series-색인-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Pandas Series 색인</a></span></li><li><span><a href="#Pandas-DataFrame-시작하기" data-toc-modified-id="Pandas-DataFrame-시작하기-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Pandas DataFrame 시작하기</a></span></li><li><span><a href="#Pandas-DataFrame-색인하기" data-toc-modified-id="Pandas-DataFrame-색인하기-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Pandas DataFrame 색인하기</a></span></li></ul></li><li><span><a href="#연산-&amp;-결측치-처리-&amp;--계층색인" data-toc-modified-id="연산-&amp;-결측치-처리-&amp;--계층색인-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>연산 &amp; 결측치 처리 &amp;  계층색인</a></span><ul class="toc-item"><li><span><a href="#연산" data-toc-modified-id="연산-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>연산</a></span></li><li><span><a href="#결측치-처리" data-toc-modified-id="결측치-처리-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>결측치 처리</a></span></li></ul></li></ul></div>

## 이번시간 배울 내용
---

`Pandas`는 파이썬에서 자주 이용되는 데이터분석 라이브러리로써 행과 열로 이루어진 데이터 객체를 만들어 다룰 수 있게 되며 보다 안정적으로 대용량의 데이터들을 처리하는데 매우 편리한 라이브러리 입니다. 


이번 시간에는 `Pandas` 패키지에 기본 개념 및 함수를 사용하여 데이터 가공을 해보도록 하겠습니다. 


○	교육 내용
1. Pandas 기본구조
1. 생성
1. 확인 
1. 접근
1. 삭제
1. 수정 및 연산
1. 데이터 적재 및 호출  


2. 연산, 결측치 처리 및 계층 색인 
3. 통계 및 집계 
4. 데이터 적재 및 호출

## Pandas 자료구조

Pandas에서는 기본적으로 `Series`와 `DataFrame` 이라는 데이터 구조를 사용하며, 다음 그림과 같습니다.

<img src='https://www.w3resource.com/w3r_images/pandas-data-structure.svg'>
<center>그림1. 데이터프레임 구성 요소</center>
<br> 

위 데이터 프레임 구성요소를 나타내면 아래와 같습니다. 

- Series: 1차원 데이터 구조, 모든 타입의 데이터를 할당 할 수 있음
- Index: 숫자 인덱스로 라벨에 접근 가능 
- DataFrame: 2차원 데이터 구조로써 관계형 데이터 베이스의 데이블 구조와 비슷, Series의 집합 
- column:  DataFrame에서 컬럼 값을 특정해서 접근가능

### Pandas Series 시작하기

In [1]:
# import
import pandas as pd  # pandas를 pd라고 별칭을 줄 수 있음

In [2]:
# series 생성
data1 = pd.Series([3, 5, 1, 2])
data1

0    3
1    5
2    1
3    2
dtype: int64

In [3]:
# pandas는 numpy 기반으로 만든 것이라는 걸 알 수 있음
type(data1.values)

numpy.ndarray

In [4]:
# 값은 모든 데이터 타입 가능
data2 = pd.Series(['big data', 30, [1, 2, 3]])
data2

0     big data
1           30
2    [1, 2, 3]
dtype: object

In [5]:
# Series 데이터를 index로 접근 가능
data2[1]  # Series[index]

30

In [6]:
# data와 index를 명시할 수 있음
pd.Series(data=(2, 5, 6, 1),
          index=['a', 'b', 'c', 'd'])

a    2
b    5
c    6
d    1
dtype: int64

### Pandas Series 색인

- 매우 빈번이 활용되므로, 필수로 숙지하여야함

In [7]:
data3 = pd.Series(data=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
                  # 이렇게 하면 알아서 매핑이 됌, but data와 size가 같아야함
                  index=list('abcdefghij')
                  )
data3

a     10
b     20
c     30
d     40
e     50
f     60
g     70
h     80
i     90
j    100
dtype: int64

In [8]:
data3 > 30

a    False
b    False
c    False
d     True
e     True
f     True
g     True
h     True
i     True
j     True
dtype: bool

In [9]:
# Series 인덱스 색인
data3[data3 > 30]

d     40
e     50
f     60
g     70
h     80
i     90
j    100
dtype: int64

In [10]:
# 30보다 크거나 같고 70보다 작은 항목만 출력
(data3 >= 30) & (data3 < 70)  # 'and'연산자가 아니라 '&'연산자!! 주의하자!!

a    False
b    False
c     True
d     True
e     True
f     True
g    False
h    False
i    False
j    False
dtype: bool

In [11]:
# 30보다 크거나 같고 70보다 작은 항목만 출력
data3[(data3 >= 30) & (data3 < 70)]

c    30
d    40
e    50
f    60
dtype: int64

<div class="alert alert-success">
    <b>예제(Exercise)</b>:
    <ul>
        <li>
        다음 시리즈를 정의하고, 뒤에서 5개 항목을 출력하여라 
        </li>
    </ul>
</div>


|||
|:--|:--:|
|A    |90|
|B    |40|
|C    |13|
|D    |26|
|E    |30|
|F    |56|
|G    |80|
|H    |92|

### Pandas DataFrame 시작하기

recall 
1. data : dataFrame에 저장할 데이터 (numpy ndarray, dict, DataFrame 등 여러 형태 가능)
1. index : 행(row) 이름, 기본값 = 0부터 1씩 증가하는 정수
1. columns : 열(column) 이름, 기본값 = 0부터 1씩 증가하는 정수
1. dtype : 데이터 형태(type), 만약 지정하지 않으면 파이썬이 자동으로 값의 형태를 보고 결정
1. copy : 입력 데이터를 복사할지 지정. 디폴트는 False 임. (복사할 거 아니면 메모리 관리 차원에서 디폴트인 False 설정 사용하면 됨)

In [12]:
# 정형데이터 데이터의 구조가 정해져있다. 

# 3. 사전 타입 데이터를 이용하여 데이터 프레임 생성하기
data = {'서울': [1053.5, 1023, 987,1],
        '경기':[1023, 1067, 1123,2],
        '충청':[512,489,487,3],
        '경상':[897, 872, 811,3],
        '전라':[451, 421, 399,4]
      }
df1 = pd.DataFrame(data)
df1

       서울    경기   충청   경상   전라
0  1053.5  1023  512  897  451
1  1023.0  1067  489  872  421
2   987.0  1123  487  811  399
3     1.0     2    3    3    4

In [13]:
# 1. 2차원 데이터 생성
df1 = pd.DataFrame([
    [1, 2, 3],
    ['kim', 'park', 'lee'],
    [1.5, 3.2, 9.1]
])
df1

     0     1    2
0    1     2    3
1  kim  park  lee
2  1.5   3.2  9.1

In [14]:
# 2. 로우 인덱스
df1.index = ['A','B','C'] # 0,1,2 -> A,B,C 로 바뀜
df1

     0     1    2
A    1     2    3
B  kim  park  lee
C  1.5   3.2  9.1

In [15]:
# 3. 컬럼 인덱스 설정
df1.columns = ['X','Y','Z']
df1

     X     Y    Z
A    1     2    3
B  kim  park  lee
C  1.5   3.2  9.1

In [16]:
# 1,2,3 한번에
df2 = pd.DataFrame(data = [[1,2,3],
                        ['kim','park','lee'],
                        [1.5, 3.2, 9.1]],
                index = ['A','B','C'],
                columns = ['X','Y','Z'])
df2

     X     Y    Z
A    1     2    3
B  kim  park  lee
C  1.5   3.2  9.1

In [17]:
# X 컬럼 조회하기 
df2['X']

A      1
B    kim
C    1.5
Name: X, dtype: object

In [18]:
# 여러 컬럼 조회하기 
# 여러 개의 컬럼들을 조회하기 위해서는 컬럼명들을 리스트로 선언해야 함.
df2[['X','Y']]

     X     Y
A    1     2
B  kim  park
C  1.5   3.2

In [19]:
# B 행 조회 
# loc를 붙임으로써 컬럼과 혼동을 방지할 수 있음 
df2.loc['B']

X     kim
Y    park
Z     lee
Name: B, dtype: object

In [20]:
# iloc 행을 인덱스로 접슨 할수 있게해준다. 
df2.iloc[1]

X     kim
Y    park
Z     lee
Name: B, dtype: object

In [21]:
# 행 인덱스로 슬라이싱 ... 
# start index 포함, end index는 포함 안됨)
df2.iloc[1:3]

     X     Y    Z
B  kim  park  lee
C  1.5   3.2  9.1

In [22]:
# 새로운 열 추가 
# 열이 없엇으면 추가로 생성하게 된다. 
df2['A'] = ['4', 'ryu',10]

In [23]:
# 새로운 행 추가 
# 새로 추가 되는 행이 인덱스가 설정되지 않았을 경우는 ignore_index=True를 해주어야된다. 

df2.append({'X':200,'Y':10,'Z':3,'A':100},ignore_index=True)

     X     Y    Z    A
0    1     2    3    4
1  kim  park  lee  ryu
2  1.5   3.2  9.1   10
3  200    10    3  100

### Pandas DataFrame 색인하기

In [24]:
df2

     X     Y    Z    A
A    1     2    3    4
B  kim  park  lee  ryu
C  1.5   3.2  9.1   10

In [25]:
# X 열에 kim 확인 
df2['X'] == 'kim'

A    False
B     True
C    False
Name: X, dtype: bool

In [26]:
# X 열에 kim 인 데이터프레임 가져오기 
df2[df2['X'] == 'kim']

     X     Y    Z    A
B  kim  park  lee  ryu

<div class="alert alert-success">
    <b>예제(Exercise)</b>:
    <ul>
        <li>
        다음 데이터 프레임을 정의하고, Price 가 200개 이하인 강의만 조건색인하여라
        </li>
    </ul>
</div>


|Class|	Year|	Price|Location|
|:--:|:--:|:--:|:--:|
|C0IoT|	2018| 100	|300|
|C02|	Network|	2017	|125|	Korea|
|C03|	Economy	|2018	|132|	Korea|
|C04|	Big Data|	2018|	312|	US|
|C05|	Cloud	|2019	|250	|France|

In [72]:
df1 = pd.DataFrame([
    ["C0IoT", 2018, 100, 300],
    ["CO2","Network", 2017, 125],
    ["CO3","Economy", 2018, 132],
    ["CO4","Big Data", 2018, 312],
    ["C05","Cloud", 2019,250]]
    ,
    columns=["Class", "Year", "Price", "Location"]
)

print(df1)
df1[df1["Price"]<2017]

# Korea 컬럼에서 300이하인 df를 구하기
df1[df1["Location"]<=300]

df1[df1["Year"]=="Economy"]

   Class      Year  Price  Location
0  C0IoT      2018    100       300
1    CO2   Network   2017       125
2    CO3   Economy   2018       132
3    CO4  Big Data   2018       312
4    C05     Cloud   2019       250

  Class     Year  Price  Location
2   CO3  Economy   2018       132

## 연산 & 결측치 처리 &  계층색인

### 연산

In [73]:
import pandas as pd
df = pd.DataFrame([[1, 3, 5, 7],
                   [2, 4, 6, 8],
                   [10, 20, 30, 40]],
                  columns=list('ABCD'), index=['X', 'Y', 'Z'])

In [28]:
df

    A   B   C   D
X   1   3   5   7
Y   2   4   6   8
Z  10  20  30  40

In [74]:
# 결측치 삭제
df.drop("X",axis=0)

    A   B   C   D
Y   2   4   6   8
Z  10  20  30  40

In [30]:
def mul2(x):
    return x * 2

In [31]:
# 보통의 경우, 파이썬에서 lambda 함수와 함께 적용한다
df.apply(lambda x: mul2(x))

    A   B   C   D
X   2   6  10  14
Y   4   8  12  16
Z  20  40  60  80

In [32]:
# 'A+B' 컬럼에 두가지를 더한 값 할당.
df['A+B'] = df['A']+df['B']

In [33]:
df

    A   B   C   D  A+B
X   1   3   5   7    4
Y   2   4   6   8    6
Z  10  20  30  40   30

### 결측치 처리

In [75]:
import numpy as np
# dropna  
df1 = pd.DataFrame([[1,2,np.nan],
                   [1,2,3],
                   [2,np.nan,4]
                   ],
                  columns=['1st score','2nd score','3rd score'])
df1

   1st score  2nd score  3rd score
0          1        2.0        NaN
1          1        2.0        3.0
2          2        NaN        4.0

In [76]:
# 결측치 삭제  결측치(놓여서 데이터가 없는 것)
df1.dropna(axis=0) # axis=0 row

   1st score  2nd score  3rd score
1          1        2.0        3.0

In [43]:
df1.dropna(axis=1) # axis=1 column

   1st score
0          1
1          1
2          2

In [44]:
# fillna 
# 평균 보간 
print(df1.mean())
display(df1.fillna(df1.mean()))

1st score    1.333333
2nd score    2.000000
3rd score    3.500000
dtype: float64

   1st score  2nd score  3rd score
0          1        2.0        3.5
1          1        2.0        3.0
2          2        2.0        4.0

In [77]:
# interpolation 
# 행단위로 보간 axis=0 
display(df1)
df1.interpolate(method='linear',limit_direction='both',axis=0)

   1st score  2nd score  3rd score
0          1        2.0        NaN
1          1        2.0        3.0
2          2        NaN        4.0

   1st score  2nd score  3rd score
0          1        2.0        3.0
1          1        2.0        3.0
2          2        2.0        4.0